const jwt = require('jsonwebtoken');
const http = require('http');
const path = require('path');
const fs = require('fs');
require('dotenv').config({ path: path.join(__dirname, '../backend/.env') });

const secret = process.env.JWT_SECRET || 'your-secret-key-change-in-production';

// User 888 payload as generated by backend auth
const token = jwt.sign({
  id: 888,
  username: 'vm_caller',
  role: 'VM Extension Telecaller',
  location_id: 2,
  store_id: 2
}, secret, { expiresIn: '1h' });

console.log('Generated test token for vm_caller');

async function runTests() {
  const csrfToken = 'test_csrf_token_secret_123';

  console.log('Step 1: Open VM Audit Draft...');
  const draftData = JSON.stringify({
    floor: 'First Floor',
    section: 'Silk Sarees (Upto Lakhs)',
    shift: 'Opening',
    locationId: 2
  });

  const draftReq = http.request({
    hostname: 'localhost',
    port: 5000,
    path: '/api/vm/audits/draft',
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(draftData),
      'Cookie': `_csrf=${csrfToken}`,
      'x-csrf-token': csrfToken
    }
  }, (draftRes) => {
    let rawDraft = '';
    draftRes.on('data', chunk => rawDraft += chunk);
    draftRes.on('end', () => {
      console.log('DRAFT STATUS:', draftRes.statusCode);
      console.log('DRAFT RESPONSE:', rawDraft.slice(0, 200));

      const draftParsed = JSON.parse(rawDraft);
      const auditId = draftParsed.auditId;
      if (!auditId) {
        console.error('Failed to get auditId from draft response');
        process.exit(1);
      }
      console.log('Obtained Audit ID:', auditId);

      // Step 2: Upload photo to POST /api/vm/photos
      console.log('Step 2: Uploading Photo to audit...');
      const boundary = '----WebKitFormBoundary7MA4YWxkTrZu0gW';
      const validJpeg = Buffer.from([
        0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, 0x4a, 0x46, 0x49, 0x46, 0x00, 0x01, 0x01, 0x01, 0x00, 0x48,
        0x00, 0x48, 0x00, 0x00, 0xff, 0xdb, 0x00, 0x43, 0x00, 0x08, 0x06, 0x06, 0x07, 0x06, 0x05, 0x08,
        0x07, 0x07, 0x07, 0x09, 0x09, 0x08, 0x0a, 0x0c, 0x14, 0x0d, 0x0c, 0x0b, 0x0b, 0x0c, 0x19, 0x12,
        0x13, 0x0f, 0x14, 0x1d, 0x1a, 0x1f, 0x1e, 0x1d, 0x1a, 0x1c, 0x1c, 0x20, 0x24, 0x2e, 0x27, 0x20,
        0x22, 0x2c, 0x23, 0x1c, 0x1c, 0x28, 0x37, 0x29, 0x2c, 0x30, 0x31, 0x34, 0x34, 0x34, 0x1f, 0x27,
        0x39, 0x3d, 0x38, 0x32, 0x3c, 0x2e, 0x33, 0x34, 0x32, 0xff, 0xc0, 0x00, 0x0b, 0x08, 0x00, 0x01,
        0x00, 0x01, 0x01, 0x01, 0x11, 0x00, 0xff, 0xc4, 0x00, 0x1f, 0x00, 0x00, 0x01, 0x05, 0x01, 0x01,
        0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x03, 0x04,
        0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0xff, 0xda, 0x00, 0x08, 0x01, 0x01, 0x00, 0x00, 0x3f,
        0x00, 0xbf, 0x00, 0xff, 0xd9
      ]);

      let header = '';
      header += `--${boundary}\r\n`;
      header += `Content-Disposition: form-data; name="submissionId"\r\n\r\n${auditId}\r\n`;
      header += `--${boundary}\r\n`;
      header += `Content-Disposition: form-data; name="floor"\r\n\r\nFirst Floor\r\n`;
      header += `--${boundary}\r\n`;
      header += `Content-Disposition: form-data; name="section"\r\n\r\nSilk Sarees (Upto Lakhs)\r\n`;
      header += `--${boundary}\r\n`;
      header += `Content-Disposition: form-data; name="locationId"\r\n\r\n2\r\n`;
      header += `--${boundary}\r\n`;
      header += `Content-Disposition: form-data; name="photo"; filename="Testimage.jpeg"\r\n`;
      header += `Content-Type: image/jpeg\r\n\r\n`;

      const bodyHeader = Buffer.from(header, 'utf-8');
      const bodyFooter = Buffer.from(`\r\n--${boundary}\r\nContent-Disposition: form-data; name="caption"\r\n\r\nVerification Test\r\n--${boundary}--\r\n`, 'utf-8');
      const fullBody = Buffer.concat([bodyHeader, validJpeg, bodyFooter]);

      const req = http.request({
        hostname: 'localhost',
        port: 5000,
        path: `/api/vm/photos`,
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': `multipart/form-data; boundary=${boundary}`,
          'Content-Length': fullBody.length,
          'Cookie': `_csrf=${csrfToken}`,
          'x-csrf-token': csrfToken
        }
      }, (res) => {
        let resData = '';
        res.on('data', chunk => resData += chunk);
        res.on('end', () => {
          console.log('UPLOAD STATUS:', res.statusCode);
          console.log('UPLOAD RESPONSE:', resData);

          try {
            const parsed = JSON.parse(resData);
            const photo = (parsed.photos && parsed.photos[0]) || parsed.photo;
            if (parsed.success && photo) {
              console.log('SUCCESS! Photo created with ID:', photo.id);
              console.log('Photo file URL:', photo.fileUrl);
              console.log('Photo stream URL:', photo.streamUrl);

              // Step 3: Verify photo can be streamed via /api/vm/photos/:id/file
              const getReq = http.request({
                hostname: 'localhost',
                port: 5000,
                path: photo.streamUrl,
                method: 'GET',
                headers: {
                  'Authorization': `Bearer ${token}`
                }
              }, (getRes) => {
                console.log('FETCH PHOTO STATUS:', getRes.statusCode);
                console.log('FETCH PHOTO CONTENT-TYPE:', getRes.headers['content-type']);
                if (getRes.statusCode === 200) {
                  console.log('>>> COMPLETE SYSTEM VERIFICATION PASSED SUCCESSFULLY! <<<');
                  process.exit(0);
                } else {
                  console.error('Fetch returned non-200');
                  process.exit(1);
                }
              });
              getReq.on('error', (e) => {
                console.error('Fetch error:', e.message);
                process.exit(1);
              });
              getReq.end();
            } else {
              console.error('Photo creation parsed check failed');
              process.exit(1);
            }
          } catch (e) {
            console.error('Error parsing response:', e);
            process.exit(1);
          }
        });
      });

      req.on('error', (err) => {
        console.error('Upload Request Error:', err);
        process.exit(1);
      });

      req.write(fullBody);
      req.end();
    });
  });

  draftReq.on('error', (e) => {
    console.error('Draft request error:', e);
    process.exit(1);
  });

  draftReq.write(draftData);
  draftReq.end();
}
runTests();

