# -*- coding: utf-8 -*-
"""BSC Enterprise Operations Platform - Complete User Manual (body PDF).

Builds the manual body (TOC + 10 sections + 15 embedded screenshots) with
ReportLab. The cover is rendered separately by cover_render.py and merged as
page 1 afterwards.
"""
import hashlib
import os

from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak, HRFlowable, Image, KeepTogether, PageBreak, Paragraph,
    SimpleDocTemplate, Spacer, Table, TableStyle,
)
from reportlab.platypus.tableofcontents import TableOfContents

# ── Fonts (Windows host fonts) ────────────────────────────────────────────
FONT_DIR = r"C:\Windows\Fonts"
pdfmetrics.registerFont(TTFont("Times New Roman", os.path.join(FONT_DIR, "times.ttf")))
pdfmetrics.registerFont(TTFont("Times New Roman-Bold", os.path.join(FONT_DIR, "timesbd.ttf")))
registerFontFamily("Times New Roman", normal="Times New Roman", bold="Times New Roman-Bold")

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f3f2f1')
SECTION_BG    = colors.HexColor('#ecebe9')
CARD_BG       = colors.HexColor('#ebeae5')
TABLE_STRIPE  = colors.HexColor('#f0efee')
HEADER_FILL   = colors.HexColor('#776b46')
COVER_BLOCK   = colors.HexColor('#80734d')
BORDER        = colors.HexColor('#d1cab7')
ICON          = colors.HexColor('#847137')
ACCENT        = colors.HexColor('#23748f')
ACCENT_2      = colors.HexColor('#39b439')
TEXT_PRIMARY  = colors.HexColor('#171715')
TEXT_MUTED    = colors.HexColor('#908d86')
SEM_SUCCESS   = colors.HexColor('#4e8b62')
SEM_WARNING   = colors.HexColor('#a28242')

TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT = colors.white
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD = TABLE_STRIPE

# ── Page geometry ─────────────────────────────────────────────────────────
PAGE_W, PAGE_H = A4
MARGIN = 2.0 * cm
AVAIL_W = PAGE_W - 2 * MARGIN
OUT_DIR = os.path.dirname(os.path.abspath(__file__))
SHOTS = os.path.join(OUT_DIR, "screenshots")

# ── Styles ────────────────────────────────────────────────────────────────
S = {}
S['h1'] = ParagraphStyle('H1', fontName='Times New Roman', fontSize=19, leading=24,
                         textColor=TEXT_PRIMARY, spaceBefore=18, spaceAfter=4)
S['h2'] = ParagraphStyle('H2', fontName='Times New Roman', fontSize=14, leading=19,
                         textColor=ACCENT, spaceBefore=14, spaceAfter=6)
S['h3'] = ParagraphStyle('H3', fontName='Times New Roman', fontSize=11.5, leading=15,
                         textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=4)
S['body'] = ParagraphStyle('Body', fontName='Times New Roman', fontSize=10.5, leading=16,
                           textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=8)
S['bullet'] = ParagraphStyle('Bullet', fontName='Times New Roman', fontSize=10.5, leading=15,
                             textColor=TEXT_PRIMARY, leftIndent=16, spaceAfter=3)
S['step'] = ParagraphStyle('Step', fontName='Times New Roman', fontSize=10.5, leading=15,
                           textColor=TEXT_PRIMARY, leftIndent=20, spaceAfter=4)
S['caption'] = ParagraphStyle('Caption', fontName='Times New Roman', fontSize=8.5, leading=11,
                              textColor=TEXT_MUTED, alignment=TA_CENTER, spaceAfter=4)
S['th'] = ParagraphStyle('TH', fontName='Times New Roman', fontSize=9.5, leading=12,
                         textColor=colors.white, alignment=TA_LEFT)
S['td'] = ParagraphStyle('TD', fontName='Times New Roman', fontSize=9.5, leading=12.5,
                         textColor=TEXT_PRIMARY, alignment=TA_LEFT)
S['callout'] = ParagraphStyle('Callout', fontName='Times New Roman', fontSize=10, leading=14.5,
                              textColor=TEXT_PRIMARY, alignment=TA_LEFT)
S['toc_title'] = ParagraphStyle('TocTitle', fontName='Times New Roman', fontSize=19, leading=24,
                                textColor=TEXT_PRIMARY, spaceAfter=14)

H1_ORPHAN_THRESHOLD = (PAGE_H - 2 * MARGIN) * 0.15
MAX_KEEP_HEIGHT = PAGE_H * 0.4

# ── TOC-aware template ────────────────────────────────────────────────────
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


def header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont('Times New Roman', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 1.1 * cm, 'BSC Enterprise Operations Platform - Complete User Manual')
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 1.25 * cm, PAGE_W - MARGIN, PAGE_H - 1.25 * cm)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 1.35 * cm, PAGE_W - MARGIN, 1.35 * cm)
    canvas.drawString(MARGIN, 1.0 * cm, 'BSC Textiles · Multi-Location Operations')
    canvas.drawRightString(PAGE_W - MARGIN, 1.0 * cm, 'Page %d' % doc.page)
    canvas.restoreState()


def add_heading(text, style, level=0, in_toc=True):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = text if in_toc else None
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    if not in_toc:
        del p.bookmark_name  # absent bookmark_name = no TOC entry
    return p


def h1(story, text):
    story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
    story.append(add_heading(text, S['h1'], level=0))
    story.append(HRFlowable(width='100%', thickness=1.4, color=ACCENT, spaceBefore=0, spaceAfter=10))


def h2(story, text, keep_with=None):
    """Sub-section heading. Level-1 headings are visual anchors only and are
    deliberately kept out of the TOC so it always fits on a single page. If
    keep_with flowables are given they are bound to the heading in one
    KeepTogether block (capped) so the heading can never be orphaned."""
    head = add_heading(text, S['h2'], level=1, in_toc=False)
    story.append(CondPageBreak(H1_ORPHAN_THRESHOLD * 0.6))
    if keep_with:
        block = [head] + list(keep_with)
        total_h = 0
        for el in block:
            _, eh = el.wrap(AVAIL_W, PAGE_H)
            total_h += eh
        if total_h <= MAX_KEEP_HEIGHT:
            story.append(KeepTogether(block))
            return
        story.append(KeepTogether(block[:2]))
        story.extend(block[2:])
        return
    story.append(head)


FIG = {'n': 0}

def figure(story, filename, caption, max_height=265, keep_with_heading=False):
    path = os.path.join(SHOTS, filename)
    pil = PILImage.open(path)
    ow, oh = pil.size
    ratio = min(AVAIL_W / ow, max_height / oh, 1.0)
    img = Image(path, width=ow * ratio, height=oh * ratio)
    img.hAlign = 'CENTER'
    FIG['n'] += 1
    cap = Paragraph('<b>Figure %d</b> - %s' % (FIG['n'], caption), S['caption'])
    block = [Spacer(1, 6), img, Spacer(1, 4), cap]
    if keep_with_heading:
        return block
    story.append(KeepTogether(block[1:]))
    story.append(Spacer(1, 8))
    return None


def para(story, text):
    story.append(Paragraph(text, S['body']))


def bullets(story, items):
    for it in items:
        story.append(Paragraph('•  %s' % it, S['bullet']))
    story.append(Spacer(1, 5))


def steps(story, items):
    for i, it in enumerate(items, 1):
        story.append(Paragraph('<b>%d.</b>  %s' % (i, it), S['step']))
    story.append(Spacer(1, 5))


def callout(story, text):
    inner = Paragraph(text, S['callout'])
    box = Table([[inner]], colWidths=[AVAIL_W * 0.96])
    box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 3, ACCENT),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
    ]))
    box.hAlign = 'CENTER'
    story.append(Spacer(1, 4))
    story.append(KeepTogether(box))
    story.append(Spacer(1, 8))


def table(story, headers, rows, ratios, caption=None):
    col_widths = [r * AVAIL_W for r in ratios]
    data = [[Paragraph('<b>%s</b>' % h, S['th']) for h in headers]]
    for row in rows:
        data.append([Paragraph(str(c), S['td']) for c in row])
    t = Table(data, colWidths=col_widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD))
    t.setStyle(TableStyle(style))
    story.append(Spacer(1, 10))
    if caption:
        cap = Paragraph(caption, S['caption'])
        story.append(KeepTogether([t, Spacer(1, 4), cap]))
    else:
        story.append(t)
    story.append(Spacer(1, 10))


# ══════════════════════════════════════════════════════════════════════════
# BUILD
# ══════════════════════════════════════════════════════════════════════════
doc = TocDocTemplate(
    os.path.join(OUT_DIR, 'manual_body.pdf'), pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN, topMargin=2.1 * cm, bottomMargin=1.9 * cm,
    title='BSC Enterprise Operations Platform - Complete User Manual',
    author='Z.ai', creator='Z.ai',
    subject='Complete user manual: Wedding CRM, Store Operations, Recruitment, Administration',
)

story = []

# ── Table of Contents ──
story.append(Paragraph('<b>Table of Contents</b>', S['toc_title']))
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle('TOC1', fontName='Times New Roman', fontSize=10.5, leading=14.5, leftIndent=6, spaceBefore=3),
    ParagraphStyle('TOC2', fontName='Times New Roman', fontSize=9, leading=12, leftIndent=24, textColor=TEXT_MUTED),
]
story.append(toc)
story.append(PageBreak())

# ══ 1. INTRODUCTION ══
h1(story, '1.  Introduction')
para(story, 'The <b>BSC Enterprise Operations Platform</b> is the internal operating system of '
     'BSC Textiles, a multi-location retail business with three divisions: <b>Belagavi</b>, '
     '<b>Davanagere</b> and <b>Shivamogga</b>. The platform unifies every front-office and '
     'back-office workflow in one place - wedding customer follow-ups, store operations, '
     'recruitment and administration - and enforces strict branch-level data isolation so that '
     'each team sees only the data that belongs to its own division.')
para(story, 'This manual walks every role through the platform section by section: how to sign in, '
     'how the dashboard reads, how each module is used day to day, and how administrators '
     'govern users, security and data. Screenshots are taken from the live system.')

h2(story, '1.1  Module Map')
table(story,
      ['Module', 'Menu Item', 'What It Does'],
      [['Wedding Follow-up CRM', 'Wedding Follow-up CRM', 'Telecalling desk for wedding shoppers: call queues, follow-ups, calendar, funnel analytics, CSV import/export, WhatsApp and e-mail reach-out.'],
       ['Store Operations', 'Hourly Footfall, Feedback, Diverts, VM Checklist, Attendance', 'Hourly visitor counts, customer feedback with CSAT analytics, sourcing diverts, visual-merchandise checks and the attendance roster.'],
       ['Recruitment', 'Candidate CRM, Offer Desk, Manpower Planning', 'Candidate pipeline from application to offer and joining, with public QR registration and designations.'],
       ['Daily Operations', 'Daily MCheck, Reports, History', 'Management checklists executed daily by store managers, with scoring, reports and audit history.'],
       ['Administration', 'Broadcast Center, System Settings', 'Company-wide announcements, user accounts, kiosk PINs, the DevTools security shield, page visibility and designations.']],
      [0.22, 0.26, 0.52],
      'Table 1 - Platform modules and their purpose')

h2(story, '1.2  Roles')
para(story, 'Every user signs in with a role that determines both the navigation menu and the data '
     'scope. Data scope is enforced on the server, not in the browser: a user assigned to '
     '<b>Belagavi</b> can never read or change Davanagere or Shivamogga records, even by calling '
     'the API directly.')
table(story,
      ['Role', 'Data Scope', 'Typical Users'],
      [['Super Admin / Admin', 'All locations', 'Head-office owners and system administrators'],
       ['HR', 'Own location', 'HR specialists running recruitment'],
       ['Manager', 'Own location', 'Store managers running daily operations'],
       ['Recruiter / Interviewer', 'Own location', 'Sourcing and interview panels'],
       ['Greeter', 'Own location', 'Entrance desk - kiosks, footfall and feedback'],
       ['Employee', 'Own location', 'Staff self-service']],
      [0.24, 0.18, 0.58],
      'Table 2 - Roles and data scope')

# ══ 2. GETTING STARTED ══
h1(story, '2.  Getting Started')
h2(story, '2.1  Signing In')
steps(story, [
    'Open the platform URL in any modern browser (Chrome, Edge, Firefox or Safari). The application works on desktop, tablet and mobile.',
    'Enter your <b>Username / E-mail</b> - for example <b>admin@bsctextiles.com</b>.',
    'Enter your <b>Password</b>. Passwords are stored as bcrypt hashes; legacy plain-text entries are upgraded automatically on first sign-in.',
    'Read the <b>Security Code</b> image and type the 4 digits it shows. The code is generated by the server, changes automatically every <b>30 seconds</b>, and a fresh one is loaded automatically if you enter it wrong.',
    'Press <b>Sign In to Dashboard</b>. A green toast confirms the welcome, and your assigned location is loaded automatically from the server - it cannot be changed from the client.',
])
figure(story, '01-login.png', 'The sign-in screen with the numeric security code. Location is assigned by the server after authentication.')
callout(story, '<b>Recovery credential:</b> the built-in master account <b>admin@bsctextiles.com</b> '
        'with password <b>admin@2026</b> always works - even before the database is seeded - and is '
        'reserved for administrators. Keep it private.')
h2(story, '2.2  Location Permission and GPS')
para(story, 'Immediately after a successful sign-in the browser may ask for <b>location permission</b>. '
     'Allowing it records the sign-in device\'s GPS coordinates in the security trail, which '
     'administrators can review in the security centre. Denying the prompt is safe - sign-in '
     'continues normally, only the location stamp is skipped.')
h2(story, '2.3  Signing Out and Sessions')
bullets(story, [
    'Click <b>Sign Out</b> at the bottom of the sidebar. The server records the sign-out in the authentication trail with its exact timestamp.',
    'Sessions are managed by the server: the session token is planted as an <b>httpOnly cookie</b> that browser JavaScript cannot read or tamper with.',
    'If you do not sign out, you are <b>logged out automatically after 6 hours</b> - the server token, the session cookie and the application timer all enforce the same limit.',
    'The sidebar collapses to a slim rail (and to a logo-only strip) with the three-line button in the top bar - useful on smaller screens.',
])

# ══ 3. DASHBOARD ══
h1(story, '3.  Executive Dashboard')
para(story, 'The dashboard is the first screen after sign-in. It is the operational pulse of the '
     'division: live counters for staff, customer feedback, the pending call queue, footfall, '
     'conversion, diverts and the feedback QR portal. Every number comes from the database and '
     'refreshes automatically every few seconds - nothing on this screen is hard-coded.')
figure(story, '02-dashboard.png', 'The Executive Operations & Workforce Hub with live KPI cards.')
h2(story, '3.1  Authentication Activity (Administrators)')
para(story, 'Administrators and Super Admins see an <b>Authentication Activity</b> panel on the '
     'dashboard. It answers "who is in the building" at a glance:')
bullets(story, [
    '<b>Sign-ins and sign-outs today</b> and over the last 7 days, with the exact timestamp of every event.',
    '<b>Active users (7 days)</b> - how many distinct people signed in this week.',
    '<b>Failed attempts</b> - repeated failures are visible immediately (and are also rate-limited automatically).',
    'A timestamped table of the most recent events with the user name, whether it was a sign-in, sign-out or failed attempt, and the IP address.',
])
figure(story, '03-dashboard-auth.png', 'Authentication Activity - every sign-in and sign-out is timestamped.')

# ══ 4. WEDDING CRM ══
h1(story, '4.  Wedding Follow-up CRM')
para(story, 'The Wedding Follow-up CRM is the telecalling heart of the platform. Wedding shoppers '
     'register an expected shopping date; telecallers work through call queues, log every '
     'conversation and drive each customer towards a store visit. The module has four tabs: '
     '<b>Wedding Follow-up Desk</b>, <b>Customer Register</b>, <b>Follow-up Calendar</b> and '
     '<b>Funnel & Performance</b>.')
fig = figure(story, '04-wedding-desk.png', 'The calling desk: KPI banner, workload counters and four call queues.', keep_with_heading=True)
h2(story, '4.1  The Calling Desk', keep_with=fig)
para(story, 'The desk opens on today\'s workload. The banner on top shows <b>Calls Pending, Calls '
     'Completed, No Answer, Callbacks</b> and <b>Remaining Calls</b>. Below it, customers are '
     'sorted into four queues, most urgent first:')
table(story,
      ['Queue', 'Who Lands Here', 'What To Do'],
      [['1. Overdue', 'Follow-up date already passed and still open', 'Call first - the card shows how many days overdue'],
       ['2. Due Today', 'Scheduled for today', 'The primary desk - work top to bottom'],
       ['3. Callback Requests', 'Customer explicitly asked for a call back', 'Honour the requested time window'],
       ['4. Upcoming (Next 7 Days)', 'Scheduled later this week', 'Prepare, do not call early']],
      [0.20, 0.38, 0.42],
      'Table 3 - The four calling queues')
callout(story, 'Each customer card shows the mobile number (tap-to-dial), a copy button, the expected '
        'shopping date, the wedding date, family size, assigned telecaller and the full conversation '
        'status - everything needed before dialling.')

h2(story, '4.2  Adding a Customer')
steps(story, [
    'Press <b>Add Wedding Customer</b> (top right).',
    'Fill in the customer name and 10-digit mobile number - the system checks for duplicates in your location as you type and warns before saving.',
    'Enter the expected shopping date (required) and, if known, the wedding date.',
    'Choose the preferred shopping category (bridal lehengas, silk sarees, sherwanis, family sets, etc.), family size and preferred call time.',
    'Optionally assign a telecaller now - otherwise the customer lands in your own queue.',
    'Set the first follow-up date and save. The customer receives a unique code like <b>WED-DAV-2026-0001</b> (location and year are part of the code).',
])

h2(story, '4.3  Logging a Call')
steps(story, [
    'Open a customer card and press the <b>Log Call</b> button.',
    'Choose the <b>outcome</b> - Shopping Confirmed, Interested, Connected, Call Back Requested, No Answer, Busy or Not Interested.',
    'Add remarks (stored encrypted), and set the <b>next follow-up date</b> and time window if the customer remains open.',
    'Save. The system updates the customer status automatically, increments the call counter and writes an audit entry.',
])
table(story,
      ['Call Outcome', 'Automatic Customer Status', 'Queue Effect'],
      [['Shopping Confirmed', 'Shopping Date Confirmed', 'Leaves the open queues; visit date updated'],
       ['Interested', 'Interested', 'Stays in follow-up flow'],
       ['Connected', 'Contacted (from New)', 'Normal follow-up continues'],
       ['Call Back Requested', 'Follow-up Pending', 'Moves to the Callback queue'],
       ['No Answer / Busy', 'Unchanged', 'Reappears in tomorrow\'s desk'],
       ['Not Interested', 'Not Interested', 'Removed from all queues (closed)']],
      [0.28, 0.30, 0.42],
      'Table 4 - Call outcomes and the status machine')

h2(story, '4.4  Customer Register')
para(story, 'The <b>Customer Register</b> tab is the full customer table with search, filters and '
     'pagination. Search matches name, mobile, customer code and e-mail. Filters narrow by '
     'date view (today, tomorrow, overdue, this week, next week or a custom range), customer '
     'status, call status and assigned telecaller. Global admins additionally get a '
     '<b>location selector</b> in the top bar; branch users are always locked to their own branch.')
figure(story, '05-wedding-register.png', 'Customer Register with filters, sorting and per-row actions.')

h2(story, '4.5  Bulk Import from CSV')
para(story, 'Lead lists can be uploaded directly from a spreadsheet. Press <b>Import CSV</b> above the '
     'register and choose a .csv file. The server reads the file, maps the common column spellings '
     'and validates every row <b>before</b> anything is written:')
bullets(story, [
    'A row needs a <b>customer name</b>, a <b>valid 10-digit Indian mobile number</b> (spaces, dashes and a +91 prefix are cleaned automatically) and a <b>parseable expected shopping date</b> (DD/MM/YYYY, DD-MM-YYYY or YYYY-MM-DD).',
    'Rows that fail validation are <b>skipped and reported with the exact reason</b> - nothing half-related enters the database.',
    'Duplicates (same mobile in the same location) are skipped as well.',
    'Optional columns: e-mail, wedding date, family size, shopping category, notes and assigned telecaller.',
    'The result toast reports how many customers were imported and how many rows were skipped.',
])
table(story,
      ['Column (any spelling)', 'Required', 'Validation'],
      [['name / customer_name', 'Yes', 'Non-empty'],
       ['mobile / phone / contact', 'Yes', '10-digit Indian mobile after normalisation'],
       ['expected_shopping_date / shopping_date', 'Yes', 'DD/MM/YYYY, DD-MM-YYYY or YYYY-MM-DD'],
       ['wedding_date, email, family_size, category, notes, telecaller', 'No', 'E-mail must contain @; family size 1-99'],
       ['follow_up_date', 'No', 'Defaults to today if omitted']],
      [0.40, 0.14, 0.46],
      'Table 5 - Accepted CSV columns and their validation')

h2(story, '4.6  Exports: CSV, Excel and PDF')
bullets(story, [
    '<b>Export CSV</b> - downloads the current view as a plain CSV file (opens anywhere).',
    '<b>Export Excel</b> - downloads a formatted .xlsx workbook of the current view.',
    '<b>Export PDF</b> - opens a print-ready branded report; use the browser\'s print dialog to save or print it.',
    'All three exports respect the active filters and the location selector - what you see is exactly what you export.',
])

h2(story, '4.7  WhatsApp and E-mail')
para(story, 'Every customer row carries one-tap outreach actions. The <b>WhatsApp</b> button opens '
     'WhatsApp with a pre-written greeting addressed to the customer; the <b>E-mail</b> button '
     'opens the mail client with a subject and body already prepared. Both use the customer\'s '
     'own mobile number and e-mail address, and appear wherever a customer row is listed.')

fig = figure(story, '06-wedding-calendar.png', 'The follow-up calendar with colour-coded workload per day.', keep_with_heading=True)
h2(story, '4.8  Follow-up Calendar', keep_with=fig)
para(story, 'The calendar shows every follow-up as a colour-coded chip on its date: <b>red for '
     'overdue</b>, <b>amber for due today</b>, <b>blue for upcoming</b> and <b>green for completed</b>. '
     'Navigate with the arrows or jump back with <b>Today</b>. Clicking a day lists that day\'s '
     'customers; entries link straight back to the customer record.')

fig = figure(story, '07-wedding-analytics.png', 'Conversion funnel, call-outcome breakdown and telecaller league table.', keep_with_heading=True)
h2(story, '4.9  Funnel and Performance', keep_with=fig)
para(story, 'The analytics tab shows how the pipeline converts - from total customers through '
     'contacted, interested, shopping-confirmed, visited to converted - together with a call-outcome '
     'breakdown and a per-telecaller performance table (assigned customers, calls completed, '
     'connections, callbacks, conversions and pending follow-ups).')

# ══ 5. STORE OPERATIONS ══
h1(story, '5.  Store Operations')
para(story, 'The Store Operations group keeps a finger on the shop floor. All modules are kiosk- and '
     'mobile-friendly and are typically operated by the greeter desk and floor managers.')
table(story,
      ['Module', 'Daily Use'],
      [['Hourly Footfall', 'Log visitor counts per hour; the dashboard totals the day and feeds the sales-conversion metric.'],
       ['Feedback Collection & QR', 'Customers scan a QR and rate the visit; negative feedback raises an instant call-queue entry for recovery calls.'],
       ['Feedback Call Queue', 'Telecallers work through feedback follow-ups; outcomes update the CSAT analytics.'],
       ['Sourcing Diverts', 'Record customers diverted between floors/sections; the dashboard counts the open ones.'],
       ['VM Checklist', 'Visual-merchandise checklist with photo evidence for the store\'s display standards.'],
       ['Attendance & Roster', 'Daily staff attendance and the section roster.'],
       ['Daily MCheck', 'Management checklists with modules, checkpoints, scoring, photo uploads, trend reports and a full audit history.']],
      [0.26, 0.74],
      'Table 6 - Store operations modules')

# ══ 6. RECRUITMENT ══
h1(story, '6.  Recruitment (Candidate CRM)')
h2(story, '6.1  Candidate Pipeline')
figure(story, '10-candidates.png', 'Candidate CRM: analytics header, status pipeline and the candidate table.')
para(story, 'Candidates flow through <b>New → Shortlisted → Selected → Offer Sent → Joined</b> (with '
     'On Hold and Rejected side pockets). The header strip filters the pipeline by status and '
     'date range; the table supports search, designation/source filters and sorting. From each '
     'row, HR logs screening calls, records interview scores, generates interview tokens and '
     'moves the candidate forward.')
intro = Paragraph('Walk-in applicants scan the QR code at reception and register themselves - no sign-in needed.', S['body'])
fig = figure(story, '11-candidate-entry.png', 'The public applicant registration form - no sign-in required.', keep_with_heading=True)
h2(story, '6.2  Public Registration (QR)', keep_with=[intro] + fig)
para(story, 'Walk-in applicants scan the QR code at reception and fill the <b>Applicant '
     'Registration</b> form themselves - personal details, designation applied for and documents. '
     'The form is public by design; the candidate lands directly in the pipeline and receives an '
     'application number like <b>BSC-2026-0001</b>.')
h2(story, '6.3  Offer Desk and Employee Directory')
para(story, 'The <b>Offer Desk</b> manages offer calls, salary and date-of-joining details, and marks '
     'candidates as joined - at which point they appear in the <b>Employee Directory</b> with their '
     'documents, section and designation. <b>Manpower Planning</b> tracks required openings per '
     'designation so hiring stays aligned with store needs.')
figure(story, '12-employees.png', 'Employee Directory - the joined workforce with profiles and documents.')

# ══ 7. ADMINISTRATION ══
h1(story, '7.  Administration')
h2(story, '7.1  User Accounts and Access')
figure(story, '08-settings-users.png', 'System Settings - user accounts, roles and location assignment.')
steps(story, [
    'Open <b>System Settings → User Accounts & Access</b>.',
    'Add a user with full name, username/e-mail, an initial password and a role.',
    'Choose the <b>location</b> the user belongs to - this single choice decides which division\'s data the account can ever see. Admin roles are location-less (all divisions).',
    'Toggle an account active/inactive or change its role at any time; changes apply at the next sign-in.',
])
h2(story, '7.2  Kiosk and Cash PINs')
para(story, 'Store kiosks (greeter desk, TV display, feedback tablets) and cash-desk actions are '
     'protected by separate numeric PINs. PINs are stored as one-way <b>bcrypt hashes</b> - they are '
     'never displayed anywhere in the application, only set or replaced here. Change them after '
     'staff rotation. Until a custom PIN is configured, kiosks accept the factory default 1234, '
     'which is immediately hashed on first use.')
h2(story, '7.3  Page Visibility Matrix')
para(story, 'The visibility matrix decides which menu items each role sees. Untick a row and the '
     'page disappears from that role\'s sidebar (the server enforces the same map, so direct URLs '
     'are blocked too).')
h2(story, '7.4  Designations and Interview Questions')
para(story, 'The designation master feeds registration dropdowns across the system; the interview '
     'question bank defines per-designation, per-round scoring sheets used by interview panels.')

# ══ 8. SECURITY CENTER ══
h1(story, '8.  Security Centre')
intro81 = Paragraph('The shield is <b>off by default</b>. In <b>System Settings \u2192 Security &amp; DevTools '
     'Shield</b> an administrator flips the switch to arm it across every device. While armed, the '
     'platform actively monitors for browser developer tools on all devices - desktop and mobile - '
     'using several independent detection signals (viewport analysis, debugger timing and a DOM '
     'probe). The moment tools are detected, the application locks behind the full-screen shield '
     'shown in Figure 12.', S['body'])
h2(story, '8.1  Developer Tools Shield (Admin-Controlled)', keep_with=[intro81])
figure(story, '15-devtools-shield.png', 'The lock screen shown whenever developer tools are detected.', max_height=230)
para(story, 'The lock lifts automatically the moment the tools are closed, and every detection is '
     'written to the audit trail - the same panel lists each event with user, timestamp and IP '
     'address. Localhost development machines are never locked, so the development team can work '
     'with tools open.')
h2(story, '8.2  GPS Sign-in Trail')
para(story, 'When users allow location permission at sign-in, the device coordinates are stored with '
     'the login event. Administrators can therefore see not only <b>when</b> someone signed in but '
     '<b>from where</b> - useful for multi-location discipline.')
h2(story, '8.3  Encryption and Data Safety')
table(story,
      ['Layer', 'Protection'],
      [['Passwords', 'bcrypt hashes; legacy plain-text rows upgrade automatically at first sign-in'],
       ['Sensitive fields', 'AES-256-GCM encryption at rest (customer notes, call remarks) with tamper detection'],
       ['Sessions', 'Signed JWT tokens with a per-deployment secret; 24-hour expiry'],
       ['Data scope', 'Location isolation enforced in every SQL query - never in the browser'],
       ['Brute force', 'Automatic rate limiting on all sign-in endpoints'],
       ['Maintenance endpoints', 'Destructive routes require an admin token and explicit confirmation']],
      [0.28, 0.72],
      'Table 7 - Security layers')

# ══ 9. RELIABILITY & TROUBLESHOOTING ══
h1(story, '9.  Reliability and Troubleshooting')
h2(story, '9.1  Working Without Internet')
figure(story, '13-offline.png', 'The animated offline banner appears the moment the connection drops.')
para(story, 'If the internet connection drops, an animated banner appears at the top of the screen - '
     'the page itself keeps working and nothing is lost. When the connection returns the banner '
     'confirms <b>"Back online"</b> and data refreshes automatically.')
fig = figure(story, '14-mobile.png', 'The full CRM adapts to phone screens - cards stack, tabs scroll, one-thumb use.', max_height=250, keep_with_heading=True)
h2(story, '9.2  Mobile and Tablets', keep_with=fig)
para(story, 'Every page is responsive: tables become card lists, menus collapse behind the '
     'three-line button and touch targets stay finger-sized. The platform is regularly used from '
     'phones on the shop floor.')
h2(story, '9.3  Common Questions')
table(story,
      ['Situation', 'What Happens / What To Do'],
      [['Too many sign-in attempts', 'Sign-in pauses for a few minutes after 50 attempts per 10 minutes - wait and retry. This protects every account.'],
       ['"Could not load..." toast', 'The server could not be reached or the database is briefly unavailable. Check the connection banner; data refreshes automatically once back online.'],
       ['A page shows "Something went wrong"', 'A rendering error was contained. Press <b>Reload Application</b> on the screen - your data is safe.'],
       ['After a platform update an open tab looks stale', 'The app detects the new version and refreshes itself once automatically.'],
       ['Forgot your password', 'Contact the System Administrator - accounts are managed in System Settings.'],
       ['Locked by the security shield', 'Close browser developer tools; the application unlocks immediately and the event is logged.']],
      [0.30, 0.70],
      'Table 8 - Troubleshooting reference')

# ══ 10. APPENDIX ══
h1(story, '10.  Appendix')
h2(story, '10.1  Wedding Customer Status Glossary')
table(story,
      ['Status', 'Meaning'],
      [['New', 'Registered, not yet called'],
       ['Contacted', 'First successful conversation done'],
       ['Interested', 'Positive response, follow-up scheduled'],
       ['Follow-up Pending', 'Customer asked for a later call'],
       ['Shopping Date Confirmed', 'Visit date agreed - high intent'],
       ['Visited Store', 'Customer came to the store'],
       ['Converted', 'Purchase completed - won'],
       ['Not Interested / Cancelled', 'Closed - excluded from all queues']],
      [0.32, 0.68],
      'Table 9 - Customer lifecycle statuses')
h2(story, '10.2  Technology Summary')
table(story,
      ['Layer', 'Technology'],
      [['Frontend', 'React 18 + TypeScript + Vite + Tailwind CSS (corporate slate-blue design system)'],
       ['Backend', 'Node.js + Express REST API with Socket.IO real-time events'],
       ['Database', 'MySQL 8 / MariaDB with a self-healing auto-initializer and performance indexes'],
       ['Security', 'JWT auth, bcrypt, AES-256-GCM field encryption, rate limiting, audit logging'],
       ['Testing', '61 automated tests: unit, white-box and black-box HTTP suites (npm test)'],
       ['Deployment', 'Hostinger Passenger - single entry point, self-building frontend']],
      [0.22, 0.78],
      'Table 10 - Technology stack at a glance')
para(story, 'For deployment instructions, environment variables and the test suite, see the '
     'repository <b>README.md</b>. For anything not covered here, contact the System '
     'Administrator or the platform development team.')
story.append(Spacer(1, 14))
story.append(HRFlowable(width='100%', thickness=1.0, color=ACCENT, spaceBefore=4, spaceAfter=6))
story.append(Paragraph('BSC Textiles · Enterprise Operations Platform · Complete User Manual · September 2026',
                       ParagraphStyle('End', fontName='Times New Roman', fontSize=9, leading=12,
                                      textColor=TEXT_MUTED, alignment=TA_CENTER)))

doc.multiBuild(story, onFirstPage=header_footer, onLaterPages=header_footer)
print('BODY OK:', os.path.join(OUT_DIR, 'manual_body.pdf'))
