import React, { useState, useRef, useEffect } from 'react';
import { X, FileText, ChevronDown } from 'lucide-react';

interface TermsAndConditionsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAccept: () => void;
}

export default function TermsAndConditionsModal({ isOpen, onClose, onAccept }: TermsAndConditionsModalProps) {
  const [agreed, setAgreed] = useState(false);
  const [scrolledToBottom, setScrolledToBottom] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!isOpen) {
      setAgreed(false);
      setScrolledToBottom(false);
    }
  }, [isOpen]);

  const handleScroll = () => {
    const el = contentRef.current;
    if (!el) return;
    const atBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 40;
    setScrolledToBottom(atBottom);
  };

  useEffect(() => {
    if (isOpen && contentRef.current) {
      contentRef.current.scrollTop = 0;
      setScrolledToBottom(false);
      setAgreed(false);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[60] bg-primary/70 backdrop-blur-md flex items-center justify-center p-4 animate-fade-in">
      <div className="bg-white rounded-3xl shadow-2xl border border-accent-soft w-full max-w-2xl max-h-[90vh] flex flex-col animate-scale-in overflow-hidden">
        {/* Header */}
        <div className="bg-primary px-6 py-4 flex items-center justify-between border-b border-accent/30 flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-accent/20 flex items-center justify-center">
              <FileText className="w-5 h-5 text-accent" />
            </div>
            <div>
              <h2 className="text-base font-black text-white tracking-tight">Terms and Conditions</h2>
              <p className="text-[10px] text-accent font-bold uppercase tracking-widest">BSC Textiles Pvt Ltd</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl text-white/70 hover:text-white hover:bg-white/10 transition-colors"
            aria-label="Close"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Scrollable Content */}
        <div
          ref={contentRef}
          onScroll={handleScroll}
          className="flex-1 overflow-y-auto px-6 py-5 space-y-5 text-[11.5px] leading-relaxed text-primary font-medium"
        >
          {/* Disclaimer */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Disclaimer</h3>
            <p className="text-primary/80">
              We work hard to keep the information and services on this Platform accurate and available, but we cannot guarantee that it will always be error-free or uninterrupted, so you use it at your own discretion and risk, subject to the rights the law gives you.
            </p>
          </section>

          <hr className="border-accent-soft" />

          {/* Terms of Use */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Terms of Use</h3>
            <p className="text-primary/80 mb-1 font-bold">What this document is.</p>
            <p className="text-primary/80 mb-2">
              This is an electronic record under the Information Technology Act, 2000 and the rules made under it. It is generated by a computer system, so it does not need a physical or digital signature. We publish it, along with our Privacy Policy, to tell you the rules for using our website and any related mobile site or app (together, the "Platform"), as required of online platforms under the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Who we are.</p>
            <p className="text-primary/80 mb-2">
              The Platform is owned and run by BSC Textiles Pvt Ltd, [a company registered under the Companies Act, 2013 / a proprietorship], with its registered office at Medical College Road, MCC B Block, Kuvempu Nagar, Davanagere-577004, Karnataka, India. In these Terms, "we", "us", and "our" mean BSC Textiles Pvt Ltd.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Who "you" are.</p>
            <p className="text-primary/80 mb-2">
              "You" means anyone who uses the Platform, whether you are just browsing, have created an account, or are buying a product or booking a service. You can look around the Platform without registering. You will need an account only for certain things, such as placing an order or managing your bookings.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Agreeing to these Terms.</p>
            <p className="text-primary/80 mb-2">
              By using the Platform, in any way, you agree to these Terms of Use. If you do not agree, please stop using the Platform. Please read them properly before you continue.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Policies that go with these Terms.</p>
            <p className="text-primary/80">
              These Terms work together with our other policies, including our Privacy Policy and our Returns and Refund Policy, which we may update from time to time. When you place an order or book a service, the policies that apply to it become part of your agreement with us. If a particular policy conflicts with these Terms for a specific order, the policy for that order applies.
            </p>
          </section>

          <hr className="border-accent-soft" />

          {/* Your Account Terms and Requirements */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Your Account Terms and Requirements</h3>
            <p className="text-primary/80 mb-1 font-bold">Keep your login private.</p>
            <p className="text-primary/80 mb-2">
              You are responsible for keeping your password, and any one-time codes we send you, safe. Please do not share them with anyone. Whatever happens through your account is treated as your activity, so if someone else uses your login, you are responsible for what they do.
            </p>
            
            <p className="text-primary/80 mb-1 font-bold">Give us the correct details.</p>
            <p className="text-primary/80 mb-2">
              When you register, please give us information that is true, complete, and up to date, and update it if it changes. If we find, or have good reason to believe, that your details are false, outdated, or incomplete, or that you have broken these Terms, we may suspend, block, or close your account and refuse you access to the Platform.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Your phone number and email.</p>
            <p className="text-primary/80 mb-2">
              We use your mobile number and email address to identify you and to contact you about your orders and account. Please keep them current. If either changes, update it in your account settings and confirm it with the one-time password (OTP) we send you. If you do not update them and something goes wrong as a result, such as missing an order update or a security alert, we cannot be held responsible for that.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Do not share your account.</p>
            <p className="text-primary/80 mb-2">
              If you let someone else use your account, they can see your account details, and you remain responsible for everything done through it. If we find that login details are being shared, we may treat it as a breach of these Terms.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Log out and tell us about problems.</p>
            <p className="text-primary/80 mb-2">
              Please log out at the end of each session, especially on shared or public devices. If you notice any unauthorised use of your account, or think your password may be known to someone else, email us immediately at exclusive@bscdvg.com.
            </p>

            <p className="text-primary/80 mb-1 font-bold">If we suspect a security problem.</p>
            <p className="text-primary/80">
              If we think your account may be misused or at risk, we may ask you to change your password, or temporarily suspend the account until the issue is sorted out. If a loss happens because you did not follow the steps above, we will not be responsible for it, but this does not affect any rights you have under the law.
            </p>
          </section>

          <hr className="border-accent-soft" />

          {/* Products and Pricing */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Products and Pricing</h3>
            <p className="text-primary/80 mb-2">
              We try to show our products as accurately as we can, but colours, sizes, and finishes may look slightly different on your screen or vary from batch to batch.
            </p>
            <ul className="list-disc pl-5 space-y-1 text-primary/80">
              <li>All prices are in Indian Rupees (INR). Whether taxes are included is stated on the product page and at checkout.</li>
              <li>Prices, offers, and availability may change without notice, but the price shown when we confirm your order is the price you pay.</li>
              <li>If a product is listed at the wrong price or is out of stock, we may cancel the order and refund anything you have paid.</li>
            </ul>
          </section>

          <hr className="border-accent-soft" />

          {/* Orders and Payments */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Orders and Payments</h3>
            <ul className="list-disc pl-5 space-y-1 text-primary/80">
              <li>Placing an order is an offer to buy. The order is accepted only when we send you an order confirmation.</li>
              <li>We may decline or cancel an order for reasons such as stock issues, pricing errors, a delivery address we cannot serve, or suspected fraud.</li>
              <li>Payments are handled by third-party payment gateways. We do not see or store your full card, UPI PIN, or net-banking details.</li>
              <li>By paying, you confirm that you are authorised to use the payment method. If a payment fails or is reversed, we may cancel the order.</li>
            </ul>
          </section>

          <hr className="border-accent-soft" />

          {/* Enquiries, Services, and Bookings */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Enquiries, Services, and Bookings</h3>
            <p className="text-primary/80 mb-2">
              Some information on the Site is general and provided for reference only. It does not create an offer or a binding commitment unless we confirm it in writing.
            </p>
            <ul className="list-disc pl-5 space-y-1 text-primary/80">
              <li>If you send us an enquiry through a form, email, or phone, we will use your details to reply, as explained in our Privacy Policy.</li>
              <li>Where you book a service, we will confirm the date, scope, and price with you. The booking is binding once we send the confirmation.</li>
              <li>We may reschedule or cancel a booking if something outside our control gets in the way, in which case we will refund any advance you paid or offer another slot.</li>
            </ul>
          </section>

          <hr className="border-accent-soft" />

          {/* Expert Consultation Services */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Expert Consultation Services</h3>
            <p className="text-primary/80 mb-2">
              Besides selling textiles, we let you get advice on design, tailoring, and fabric choices from experienced specialists ("Experts").
            </p>

            <p className="text-primary/80 mb-1 font-bold">Advice, not a guarantee.</p>
            <p className="text-primary/80 mb-2">
              An Expert's suggestions are their own professional opinion, based on what you tell and show them. They are there to help you decide, but the final choice of fabric, design, size, and style is always yours. We cannot promise that any advice will suit your needs or give a particular result.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Distance has its limits.</p>
            <p className="text-primary/80 mb-2">
              Experts cannot touch the fabric or take your measurements in person during an online session. Advice on fit, drape, or colour given from a distance can be a little off. For garments that must fit exactly, we suggest asking for a fabric sample or an in-person fitting first.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Give us accurate details.</p>
            <p className="text-primary/80 mb-2">
              The measurements, photos, and instructions you share are your responsibility, and we do not check them. If they are wrong or unclear, the final product may not suit you, and we cannot be held responsible for that.
            </p>

            <p className="text-primary/80 mb-1 font-bold">How the session works.</p>
            <p className="text-primary/80 mb-2">
              The Expert may choose the format (video, call, chat, or in person) that best suits your request. If the Expert feels they cannot help properly, they may decline the session, and we will offer you a refund or another slot.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Orders based on an Expert's advice.</p>
            <p className="text-primary/80 mb-2">
              If you place an order after a consultation, it is treated like any other order under these Terms. An Expert may suggest a different fabric or design. We will only go ahead with the change if you agree to it and the item is available.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Views of the Experts.</p>
            <p className="text-primary/80 mb-2">
              Experts use their own judgment, and their opinions are theirs, not ours. If an Expert behaves unprofessionally, please tell us at exclusive@bscdvg.com.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Booking for someone else.</p>
            <p className="text-primary/80 mb-2">
              If you book on behalf of another person, please make sure you have their permission before sharing their measurements or photos.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Your information.</p>
            <p className="text-primary/80 mb-2">
              We use the measurements, photos, and messages you share only to run the consultation and complete your order. Experts may keep notes about your preferences so they can help you better next time. You can ask us to delete these at any time.
            </p>

            <p className="text-primary/80 mb-1 font-bold">Fees, changes, and refunds.</p>
            <p className="text-primary/80">
              The consultation fee is shown before you pay. If the Expert does not show up, or we cannot hold the session because of a problem on our side, we will offer you a new slot or a full refund. Once a session has taken place, the fee is not refundable, unless the law says otherwise.
            </p>
          </section>

          <hr className="border-accent-soft" />

          {/* Marketplace Sellers */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Marketplace Sellers</h3>
            <p className="text-primary/80 mb-2">Parts of the Site let independent sellers list and sell their products ("Sellers"). For those products:</p>
            <ul className="list-disc pl-5 space-y-1 text-primary/80">
              <li>We act as a platform that connects buyers and Sellers. The sale is between you and the Seller.</li>
              <li>Sellers are responsible for describing their products accurately, for their quality and legality, for their prices, and for meeting their own legal obligations, including invoicing and taxes.</li>
              <li>If you have a problem with a Seller's product or service, contact us at exclusive@bscdvg.com. We will help you reach a resolution.</li>
              <li>We may remove any Seller or listing that breaks the law, our policies, or these Terms.</li>
            </ul>
          </section>

          <hr className="border-accent-soft" />

          {/* Shipping and Delivery */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Shipping and Delivery</h3>
            <ul className="list-disc pl-5 space-y-1 text-primary/80">
              <li>Delivery timelines and charges are shown at checkout. Timelines are estimates, and delays caused by couriers, weather, or events outside our control are not guaranteed against.</li>
              <li>Please provide a full and correct delivery address and phone number. If a delivery fails because of wrong details, extra charges may apply.</li>
              <li>Please check the parcel on arrival and tell us within 48 hours if it is damaged or wrong.</li>
            </ul>
          </section>

          <hr className="border-accent-soft" />

          {/* Cancellations, Returns, and Refunds */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Cancellations, Returns, and Refunds</h3>
            <ul className="list-disc pl-5 space-y-1 text-primary/80">
              <li><strong>Cancellations:</strong> You can cancel an order before it is shipped by emailing exclusive@bscdvg.com. Once shipped, the return process applies.</li>
              <li><strong>Returns:</strong> You can request a return within the allowed days of delivery if the product is defective, damaged, or not what you ordered. The product must be unused, in its original condition and packaging.</li>
              <li><strong>How to return:</strong> Write to us at exclusive@bscdvg.com with your order number and photos of the product.</li>
              <li><strong>Refunds:</strong> Once we receive and check a returned item, we will refund the amount to your original payment method.</li>
              <li>Products bought from Sellers are subject to the return terms shown on the product page, in addition to this section.</li>
            </ul>
          </section>

          <hr className="border-accent-soft" />

          {/* Messages and Marketing */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Messages and Marketing</h3>
            <p className="text-primary/80">
              We will send you messages about your orders, bookings, and account through email, SMS, and WhatsApp. These are essential. We will send promotional messages and offers only if you have opted in. You can opt out at any time by emailing exclusive@bscdvg.com. Opting out of promotions will not stop your order and account messages.
            </p>
          </section>

          <hr className="border-accent-soft" />

          {/* Our Content and Intellectual Property */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Our Content and Intellectual Property</h3>
            <p className="text-primary/80">
              The Site's text, images, logos, product photos, designs, and software belong to us or are used with permission, and are protected by Indian intellectual property laws. You may view and use them for your own personal, non-commercial purposes. Any other use, including copying, adapting, or selling them, needs our written permission first.
            </p>
          </section>

          <hr className="border-accent-soft" />

          {/* You Agree and Confirm */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">You Agree and Confirm</h3>
            <p className="text-primary/80 mb-2">By using the Platform, you agree and confirm the following:</p>
            <ol className="list-decimal pl-5 space-y-2 text-primary/80">
              <li><strong>You will follow the law.</strong> You will use the Platform and place orders in line with all Indian laws that apply. You will not use the Platform for any unlawful purpose.</li>
              <li><strong>We connect you with Sellers.</strong> For products listed by independent sellers, we provide the technology that lets you find them and place an order. The sale is between you and the Seller.</li>
              <li><strong>Sellers are independent businesses.</strong> Each Seller decides what to list and at what price, and is responsible for the quality of their products.</li>
              <li><strong>Your orders are genuine.</strong> You are placing orders in good faith, with correct details, and you intend to pay for them and accept delivery.</li>
              <li><strong>We will still help you.</strong> If something goes wrong with a Seller's product or service, contact us at exclusive@bscdvg.com. We will help you reach a fair resolution.</li>
            </ol>
          </section>

          <hr className="border-accent-soft" />

          {/* Indemnity */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Indemnity</h3>
            <p className="text-primary/80">
              If your breach of these Terms or misuse of the Site leads to a claim, loss, or expense for us (including reasonable legal costs), you agree to cover it.
            </p>
          </section>

          <hr className="border-accent-soft" />

          {/* Governing Law */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Governing Law</h3>
            <p className="text-primary/80">
              These Terms are governed by the laws of India. If a dispute arises, please write to us first at exclusive@bscdvg.com so we can try to sort it out. If it cannot be resolved that way, the courts at Davanagere, Karnataka will have jurisdiction, without affecting any rights you have under consumer protection law.
            </p>
          </section>

          <hr className="border-accent-soft" />

          {/* Grievance Officer */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Grievance Officer</h3>
            <p className="text-primary/80 mb-2">In line with the Information Technology Act, 2000, you can raise complaints with our Grievance Officer:</p>
            <ul className="list-none space-y-1 text-primary/80">
              <li><strong>Email:</strong> exclusive@bscdvg.com</li>
              <li><strong>Phone:</strong> 9071555508</li>
              <li><strong>Address:</strong> BSC Textiles Pvt Ltd, Medical College Road, MCC B Block, Kuvempu Nagar, Davanagere, Karnataka 577004</li>
              <li><strong>Hours:</strong> Monday to Saturday, 10:00 AM to 9:30 PM IST</li>
            </ul>
          </section>

          <hr className="border-accent-soft" />

          {/* Changes to These Terms */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Changes to These Terms</h3>
            <p className="text-primary/80">
              We may update these Terms from time to time. The latest version will always be on this page. If you keep using the Site after an update, we will take it that you accept the new Terms.
            </p>
          </section>

          <hr className="border-accent-soft" />

          {/* Contact Us */}
          <section>
            <h3 className="text-sm font-black text-primary mb-2 tracking-tight">Contact Us</h3>
            <p className="text-primary/80 mb-2">If you have a question about your order, your account, or these Terms, our support team is happy to help.</p>
            <ul className="list-none space-y-1 text-primary/80">
              <li><strong>Email:</strong> exclusive@bscdvg.com</li>
              <li><strong>Phone:</strong> 9071555508</li>
              <li><strong>Support hours:</strong> Monday to Saturday, 10:00 AM to 9:30 PM IST</li>
              <li><strong>Address:</strong> BSC Textiles Pvt Ltd, Medical College Road, MCC B Block, Kuvempu Nagar, Davanagere, Karnataka 577004</li>
            </ul>
          </section>
        </div>

        {/* Footer — Agree & Accept */}
        <div className="border-t border-accent-soft px-6 py-4 bg-background/50 flex-shrink-0 space-y-3">
          {!scrolledToBottom && (
            <p className="text-[10px] text-primary/60 font-medium flex items-center gap-1.5">
              <ChevronDown className="w-3 h-3 animate-bounce" />
              Please scroll through the Terms and Conditions to enable the agreement checkbox.
            </p>
          )}
          <label className={`flex items-start gap-3 cursor-pointer ${!scrolledToBottom ? 'opacity-50 pointer-events-none' : ''}`}>
            <input
              type="checkbox"
              checked={agreed}
              onChange={(e) => setAgreed(e.target.checked)}
              disabled={!scrolledToBottom}
              className="mt-0.5 w-4 h-4 rounded border-accent-soft text-primary focus:ring-accent/30 accent-primary"
            />
            <span className="text-[11px] font-semibold text-primary leading-snug">
              I have read and agree to the{' '}
              <span className="font-black">Terms and Conditions</span>{' '}
              of BSC Textiles Pvt Ltd.
            </span>
          </label>
          <div className="flex items-center justify-end gap-3">
            <button
              onClick={onClose}
              className="px-5 py-2.5 rounded-xl border border-accent-soft text-primary font-bold text-xs hover:bg-background transition-all"
            >
              Close
            </button>
            <button
              onClick={() => { if (agreed) onAccept(); }}
              disabled={!agreed}
              className="px-6 py-2.5 rounded-xl bg-primary text-white font-extrabold text-xs tracking-wide hover:bg-primary-hover transition-all shadow-lg shadow-primary/20 disabled:opacity-40 disabled:cursor-not-allowed flex items-center gap-2"
            >
              <FileText className="w-4 h-4" />
              I Agree & Continue
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
